openapi: 3.0.0
info:
  title: Fintech API
  description: API documentation for the Fintech project
  version: 1.0.0
servers:
  - url: http://localhost:7070/api
paths:
  /Auth:
    get:
      summary: Get all users
      responses:
        '200':
          description: List of users
  /transactions:
    post:
      summary: Create a new transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                type:
                  type: string
      responses:
        '201':
          description: Transaction created
